# Default colors
[colors.primary]
background = '#1c1c1c'
foreground = '#d0d0d0'

# Normal colors
[colors.normal]
black   = "#282828"  
red     = "#f25f5c"  
green   = "#58a75c"  
yellow  = "#e0a800"  
blue    = "#5b8fb9"  
magenta = "#9b6c8d"  
cyan    = "#63b7b1"  
white   = "#d0d0d0"  

# Bright color
[colors.bright]
black   = "#383838" 
red     = "#e06c75" 
green   = "#98c379" 
yellow  = "#d19a66" 
blue    = "#61afef" 
magenta = "#c678dd" 
cyan    = "#56b6c2" 
white   = "#ffffff" 

# Cursor colors
[colors.cursor]
text     = "#1c1c1c" 
cursor   = "#61afef" 

# Selection colors
[colors.selection]
text  = "#1c1c1c" 

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"
